# Site settings
title: ""
description: ""

# Build settings
markdown: kramdown
sass:
   sass_dir: _sass
   style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "MD MOSADDEK-AL-HAMEEM"
resume_title: ""

# used for the contact button in _layouts/resume.html
resume_contact_email: "hameemroot@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "01571-503060"
resume_contact_address: "Mirpur-1, Dhaka, Bangladesh"

resume_header_contact_info: ""
display_header_contact_info: "true"

resume_header_intro: "<p>Dedicated web developer and IT enthusiast with a passion for creating dynamic and user-friendly websites. Proficient in programming languages and frameworks, I possess a strong foundation in front-end development. Committed to staying updated with the latest industry trends and continuously expanding my skill set to deliver innovative solutions</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: false
resume_section_links: false
resume_section_associations: false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
   resume_github_url: "https://github.com/mdhameem"
   #resume_twitter_url: "http://twitter.com/jglovier"
   #resume_dribbble_url: "https://dribbble.com/jag"
   # resume_facebook_url:          "insert Facebook URL here"
   resume_linkedin_url: "https://www.linkedin.com/in/md-mosaddek-al-hameem-0b7941286/"
   # resume_instagram_url:         "insert your Instagram URL here"
   resume_website_url: "https://mdhameem.github.io"
   #resume_medium_url: "https://medium.com/@jglovier"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
